#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT_DIR/tests/assert.sh"

assert_contains "BitrixVM Backup" "$ROOT_DIR/README.md"
assert_contains "curl -fsSL https://raw.githubusercontent.com/MrDeff/bitrixvm-backup/main/install.sh" "$ROOT_DIR/README.md"
assert_contains "bitrix-backup-run --config" "$ROOT_DIR/README.md"
assert_contains "RUN_INTEGRATION=1 bash tests/run.sh" "$ROOT_DIR/README.md"
assert_contains "Agent Notes" "$ROOT_DIR/AGENTS.md"
assert_contains "Do not commit real" "$ROOT_DIR/AGENTS.md"
assert_contains "kind:db" "$ROOT_DIR/AGENTS.md"
assert_contains "install.sh" "$ROOT_DIR/AGENTS.md"
assert_contains "ExecStart=/opt/bitrix-backup/bin/bitrix-backup-run --config /etc/bitrix-backup/sites.yml" "$ROOT_DIR/systemd/bitrix-backup.service"
assert_contains "OnCalendar=*-*-* 03:15:00" "$ROOT_DIR/systemd/bitrix-backup.timer"
assert_contains "Persistent=true" "$ROOT_DIR/systemd/bitrix-backup.timer"
assert_contains "RandomizedDelaySec=20m" "$ROOT_DIR/systemd/bitrix-backup.timer"
assert_contains "WantedBy=timers.target" "$ROOT_DIR/systemd/bitrix-backup.timer"
assert_contains "python3-pyyaml" "$ROOT_DIR/docs/install.md"
assert_contains "curl -fsSL https://raw.githubusercontent.com/MrDeff/bitrixvm-backup/main/install.sh" "$ROOT_DIR/docs/install.md"
assert_contains "rsync" "$ROOT_DIR/docs/install.md"
assert_contains "--repo-prefix sftp:backup@example-backup-host:/srv/restic" "$ROOT_DIR/docs/install.md"
assert_contains "/etc/bitrix-backup/sites/example-com.env" "$ROOT_DIR/docs/install.md"
assert_contains "RESTIC_PASSWORD" "$ROOT_DIR/docs/install.md"
assert_contains "restic init" "$ROOT_DIR/docs/storage-sftp.md"
assert_contains "RESTIC_PASSWORD" "$ROOT_DIR/docs/storage-sftp.md"
assert_contains "/etc/bitrix-backup/sites/example-com.env" "$ROOT_DIR/docs/storage-sftp.md"
assert_contains "AWS_ACCESS_KEY_ID" "$ROOT_DIR/docs/storage-s3.md"
assert_contains "AWS_SECRET_ACCESS_KEY" "$ROOT_DIR/docs/storage-s3.md"
assert_contains "AWS_DEFAULT_REGION" "$ROOT_DIR/docs/storage-s3.md"
assert_contains "RESTIC_PASSWORD" "$ROOT_DIR/docs/storage-s3.md"
assert_contains "/etc/bitrix-backup/sites/example-com.env" "$ROOT_DIR/docs/storage-s3.md"
assert_contains "bitrix-backup-restore" "$ROOT_DIR/docs/restore.md"
assert_contains "/restore/example-com/<restore-id>/files" "$ROOT_DIR/docs/restore.md"
assert_contains "/restore/example-com/<restore-id>/db/db.sql" "$ROOT_DIR/docs/restore.md"
assert_contains "--files-snapshot files-snapshot-id" "$ROOT_DIR/docs/restore.md"
assert_contains "--db-snapshot db-snapshot-id" "$ROOT_DIR/docs/restore.md"

printf 'ok - docs\n'
